name: Yaml Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lintDefinitions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint YAML sources with yamllint
      run: |
        yamllint --version
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        format: github
        config_data: |
          extends: default
          rules:
            document-start:
              level: error
            line-length: disable
            key-duplicates: disable
            truthy: disable
            comments:
              min-spaces-from-content: 1
